name: ADRs2

on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo principal
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install yfinance pandas matplotlib numpy

      - name: Run script
        run: python ADR.py

      - name: Subir CSV al repo destino con token
        run: |
          mkdir tmp_repo
          cp Precios_ADRs.csv ADRs_variacion_porcentual_diaria.csv tmp_repo/
          cd tmp_repo
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git branch -M main
          git add Precios_ADRs.csv ADRs_variacion_porcentual_diaria.csv
          git commit -m "Auto-update: resultados $(date +'%Y-%m-%d %H:%M')" || echo "No hay cambios"
          git remote add origin https://x-access-token:${{ secrets.CJRA824 }}@github.com/jesusrobles824/bases-de-datos.git
          git push -f origin main
